/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _obstacle_map_message_t_h
#define _obstacle_map_message_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _obstacle_map_message_t obstacle_map_message_t;
struct _obstacle_map_message_t
{
    int8_t     type;
    float      resolution;
    int32_t    num_rows;
    int32_t    num_cols;
    int32_t    map_r0;
    int32_t    map_c0;
    int32_t    array_r0;
    int32_t    array_c0;
    int64_t    length;
    int8_t     *data;
};
 
obstacle_map_message_t   *obstacle_map_message_t_copy(const obstacle_map_message_t *p);
void obstacle_map_message_t_destroy(obstacle_map_message_t *p);

typedef struct _obstacle_map_message_t_subscription_t obstacle_map_message_t_subscription_t;
typedef void(*obstacle_map_message_t_handler_t)(const lcm_recv_buf_t *rbuf, 
             const char *channel, const obstacle_map_message_t *msg, void *user);

int obstacle_map_message_t_publish(lcm_t *lcm, const char *channel, const obstacle_map_message_t *p);
obstacle_map_message_t_subscription_t* obstacle_map_message_t_subscribe(lcm_t *lcm, const char *channel, obstacle_map_message_t_handler_t f, void *userdata);
int obstacle_map_message_t_unsubscribe(lcm_t *lcm, obstacle_map_message_t_subscription_t* hid);

int  obstacle_map_message_t_encode(void *buf, int offset, int maxlen, const obstacle_map_message_t *p);
int  obstacle_map_message_t_decode(const void *buf, int offset, int maxlen, obstacle_map_message_t *p);
int  obstacle_map_message_t_decode_cleanup(obstacle_map_message_t *p);
int  obstacle_map_message_t_encoded_size(const obstacle_map_message_t *p);

// LCM support functions. Users should not call these
int64_t __obstacle_map_message_t_get_hash(void);
int64_t __obstacle_map_message_t_hash_recursive(const __lcm_hash_ptr *p);
int     __obstacle_map_message_t_encode_array(void *buf, int offset, int maxlen, const obstacle_map_message_t *p, int elements);
int     __obstacle_map_message_t_decode_array(const void *buf, int offset, int maxlen, obstacle_map_message_t *p, int elements);
int     __obstacle_map_message_t_decode_array_cleanup(obstacle_map_message_t *p, int elements);
int     __obstacle_map_message_t_encoded_array_size(const obstacle_map_message_t *p, int elements);
int     __obstacle_map_message_t_clone_array(const obstacle_map_message_t *p, obstacle_map_message_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
