/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "point_cloud_message_t.h"

static int __point_cloud_message_t_hash_computed;
static int64_t __point_cloud_message_t_hash;
 
int64_t __point_cloud_message_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __point_cloud_message_t_get_hash)
            return 0;
 
    const __lcm_hash_ptr cp = { p, (void*)__point_cloud_message_t_get_hash };
    (void) cp;
 
    int64_t hash = 0x7f3c78e6e4ccdd11LL
         + __int64_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
        ;
 
    return (hash<<1) + ((hash>>63)&1);
}
 
int64_t __point_cloud_message_t_get_hash(void)
{
    if (!__point_cloud_message_t_hash_computed) {
        __point_cloud_message_t_hash = __point_cloud_message_t_hash_recursive(NULL);
        __point_cloud_message_t_hash_computed = 1;
    }
 
    return __point_cloud_message_t_hash;
}
 
int __point_cloud_message_t_encode_array(void *buf, int offset, int maxlen, const point_cloud_message_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].count), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].x, p[element].count);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].y, p[element].count);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].z, p[element].count);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, p[element].r, p[element].count);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, p[element].g, p[element].count);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, p[element].b, p[element].count);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int point_cloud_message_t_encode(void *buf, int offset, int maxlen, const point_cloud_message_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __point_cloud_message_t_get_hash();
 
    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    thislen = __point_cloud_message_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int __point_cloud_message_t_encoded_array_size(const point_cloud_message_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {
 
        size += __int64_t_encoded_array_size(&(p[element].count), 1);
 
        size += __float_encoded_array_size(p[element].x, p[element].count);
 
        size += __float_encoded_array_size(p[element].y, p[element].count);
 
        size += __float_encoded_array_size(p[element].z, p[element].count);
 
        size += __int8_t_encoded_array_size(p[element].r, p[element].count);
 
        size += __int8_t_encoded_array_size(p[element].g, p[element].count);
 
        size += __int8_t_encoded_array_size(p[element].b, p[element].count);
 
    }
    return size;
}
 
int point_cloud_message_t_encoded_size(const point_cloud_message_t *p)
{
    return 8 + __point_cloud_message_t_encoded_array_size(p, 1);
}
 
int __point_cloud_message_t_decode_array(const void *buf, int offset, int maxlen, point_cloud_message_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].count), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].x = (float*) lcm_malloc(sizeof(float) * p[element].count);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].x, p[element].count);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].y = (float*) lcm_malloc(sizeof(float) * p[element].count);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].y, p[element].count);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].z = (float*) lcm_malloc(sizeof(float) * p[element].count);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].z, p[element].count);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].r = (int8_t*) lcm_malloc(sizeof(int8_t) * p[element].count);
        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, p[element].r, p[element].count);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].g = (int8_t*) lcm_malloc(sizeof(int8_t) * p[element].count);
        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, p[element].g, p[element].count);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].b = (int8_t*) lcm_malloc(sizeof(int8_t) * p[element].count);
        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, p[element].b, p[element].count);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int __point_cloud_message_t_decode_array_cleanup(point_cloud_message_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int64_t_decode_array_cleanup(&(p[element].count), 1);
 
        __float_decode_array_cleanup(p[element].x, p[element].count);
        if (p[element].x) free(p[element].x);
 
        __float_decode_array_cleanup(p[element].y, p[element].count);
        if (p[element].y) free(p[element].y);
 
        __float_decode_array_cleanup(p[element].z, p[element].count);
        if (p[element].z) free(p[element].z);
 
        __int8_t_decode_array_cleanup(p[element].r, p[element].count);
        if (p[element].r) free(p[element].r);
 
        __int8_t_decode_array_cleanup(p[element].g, p[element].count);
        if (p[element].g) free(p[element].g);
 
        __int8_t_decode_array_cleanup(p[element].b, p[element].count);
        if (p[element].b) free(p[element].b);
 
    }
    return 0;
}
 
int point_cloud_message_t_decode(const void *buf, int offset, int maxlen, point_cloud_message_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __point_cloud_message_t_get_hash();
 
    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;
 
    thislen = __point_cloud_message_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int point_cloud_message_t_decode_cleanup(point_cloud_message_t *p)
{
    return __point_cloud_message_t_decode_array_cleanup(p, 1);
}
 
int __point_cloud_message_t_clone_array(const point_cloud_message_t *p, point_cloud_message_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int64_t_clone_array(&(p[element].count), &(q[element].count), 1);
 
        q[element].x = (float*) lcm_malloc(sizeof(float) * q[element].count);
        __float_clone_array(p[element].x, q[element].x, p[element].count);
 
        q[element].y = (float*) lcm_malloc(sizeof(float) * q[element].count);
        __float_clone_array(p[element].y, q[element].y, p[element].count);
 
        q[element].z = (float*) lcm_malloc(sizeof(float) * q[element].count);
        __float_clone_array(p[element].z, q[element].z, p[element].count);
 
        q[element].r = (int8_t*) lcm_malloc(sizeof(int8_t) * q[element].count);
        __int8_t_clone_array(p[element].r, q[element].r, p[element].count);
 
        q[element].g = (int8_t*) lcm_malloc(sizeof(int8_t) * q[element].count);
        __int8_t_clone_array(p[element].g, q[element].g, p[element].count);
 
        q[element].b = (int8_t*) lcm_malloc(sizeof(int8_t) * q[element].count);
        __int8_t_clone_array(p[element].b, q[element].b, p[element].count);
 
    }
    return 0;
}
 
point_cloud_message_t *point_cloud_message_t_copy(const point_cloud_message_t *p)
{
    point_cloud_message_t *q = (point_cloud_message_t*) malloc(sizeof(point_cloud_message_t));
    __point_cloud_message_t_clone_array(p, q, 1);
    return q;
}
 
void point_cloud_message_t_destroy(point_cloud_message_t *p)
{
    __point_cloud_message_t_decode_array_cleanup(p, 1);
    free(p);
}
 
int point_cloud_message_t_publish(lcm_t *lc, const char *channel, const point_cloud_message_t *p)
{
      int max_data_size = point_cloud_message_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = point_cloud_message_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _point_cloud_message_t_subscription_t {
    point_cloud_message_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void point_cloud_message_t_handler_stub (const lcm_recv_buf_t *rbuf, 
                            const char *channel, void *userdata)
{
    int status;
    point_cloud_message_t p;
    memset(&p, 0, sizeof(point_cloud_message_t));
    status = point_cloud_message_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding point_cloud_message_t!!!\n", status);
        return;
    }

    point_cloud_message_t_subscription_t *h = (point_cloud_message_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    point_cloud_message_t_decode_cleanup (&p);
}

point_cloud_message_t_subscription_t* point_cloud_message_t_subscribe (lcm_t *lcm, 
                    const char *channel, 
                    point_cloud_message_t_handler_t f, void *userdata)
{
    point_cloud_message_t_subscription_t *n = (point_cloud_message_t_subscription_t*)
                       malloc(sizeof(point_cloud_message_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel, 
                                 point_cloud_message_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg point_cloud_message_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int point_cloud_message_t_unsubscribe(lcm_t *lcm, point_cloud_message_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr, 
           "couldn't unsubscribe point_cloud_message_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

