/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _point_cloud_message_t_h
#define _point_cloud_message_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _point_cloud_message_t point_cloud_message_t;
struct _point_cloud_message_t
{
    int64_t    count;
    float      **points;
    int8_t     **colors;
};
 
point_cloud_message_t   *point_cloud_message_t_copy(const point_cloud_message_t *p);
void point_cloud_message_t_destroy(point_cloud_message_t *p);

typedef struct _point_cloud_message_t_subscription_t point_cloud_message_t_subscription_t;
typedef void(*point_cloud_message_t_handler_t)(const lcm_recv_buf_t *rbuf, 
             const char *channel, const point_cloud_message_t *msg, void *user);

int point_cloud_message_t_publish(lcm_t *lcm, const char *channel, const point_cloud_message_t *p);
point_cloud_message_t_subscription_t* point_cloud_message_t_subscribe(lcm_t *lcm, const char *channel, point_cloud_message_t_handler_t f, void *userdata);
int point_cloud_message_t_unsubscribe(lcm_t *lcm, point_cloud_message_t_subscription_t* hid);

int  point_cloud_message_t_encode(void *buf, int offset, int maxlen, const point_cloud_message_t *p);
int  point_cloud_message_t_decode(const void *buf, int offset, int maxlen, point_cloud_message_t *p);
int  point_cloud_message_t_decode_cleanup(point_cloud_message_t *p);
int  point_cloud_message_t_encoded_size(const point_cloud_message_t *p);

// LCM support functions. Users should not call these
int64_t __point_cloud_message_t_get_hash(void);
int64_t __point_cloud_message_t_hash_recursive(const __lcm_hash_ptr *p);
int     __point_cloud_message_t_encode_array(void *buf, int offset, int maxlen, const point_cloud_message_t *p, int elements);
int     __point_cloud_message_t_decode_array(const void *buf, int offset, int maxlen, point_cloud_message_t *p, int elements);
int     __point_cloud_message_t_decode_array_cleanup(point_cloud_message_t *p, int elements);
int     __point_cloud_message_t_encoded_array_size(const point_cloud_message_t *p, int elements);
int     __point_cloud_message_t_clone_array(const point_cloud_message_t *p, point_cloud_message_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
