/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _quad_mesh_message_t_h
#define _quad_mesh_message_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _quad_mesh_message_t quad_mesh_message_t;
struct _quad_mesh_message_t
{
    int32_t    image_width;
    int32_t    image_height;
    int64_t    image_size;
    int8_t     *image_data;
    int64_t    num_vertices;
    float      *vertex_x;
    float      *vertex_y;
    float      *vertex_z;
    float      *tex_coord_x;
    float      *tex_coord_y;
};
 
quad_mesh_message_t   *quad_mesh_message_t_copy(const quad_mesh_message_t *p);
void quad_mesh_message_t_destroy(quad_mesh_message_t *p);

typedef struct _quad_mesh_message_t_subscription_t quad_mesh_message_t_subscription_t;
typedef void(*quad_mesh_message_t_handler_t)(const lcm_recv_buf_t *rbuf, 
             const char *channel, const quad_mesh_message_t *msg, void *user);

int quad_mesh_message_t_publish(lcm_t *lcm, const char *channel, const quad_mesh_message_t *p);
quad_mesh_message_t_subscription_t* quad_mesh_message_t_subscribe(lcm_t *lcm, const char *channel, quad_mesh_message_t_handler_t f, void *userdata);
int quad_mesh_message_t_unsubscribe(lcm_t *lcm, quad_mesh_message_t_subscription_t* hid);

int  quad_mesh_message_t_encode(void *buf, int offset, int maxlen, const quad_mesh_message_t *p);
int  quad_mesh_message_t_decode(const void *buf, int offset, int maxlen, quad_mesh_message_t *p);
int  quad_mesh_message_t_decode_cleanup(quad_mesh_message_t *p);
int  quad_mesh_message_t_encoded_size(const quad_mesh_message_t *p);

// LCM support functions. Users should not call these
int64_t __quad_mesh_message_t_get_hash(void);
int64_t __quad_mesh_message_t_hash_recursive(const __lcm_hash_ptr *p);
int     __quad_mesh_message_t_encode_array(void *buf, int offset, int maxlen, const quad_mesh_message_t *p, int elements);
int     __quad_mesh_message_t_decode_array(const void *buf, int offset, int maxlen, quad_mesh_message_t *p, int elements);
int     __quad_mesh_message_t_decode_array_cleanup(quad_mesh_message_t *p, int elements);
int     __quad_mesh_message_t_encoded_array_size(const quad_mesh_message_t *p, int elements);
int     __quad_mesh_message_t_clone_array(const quad_mesh_message_t *p, quad_mesh_message_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
