/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "quad_mesh_message_t.h"

static int __quad_mesh_message_t_hash_computed;
static int64_t __quad_mesh_message_t_hash;
 
int64_t __quad_mesh_message_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __quad_mesh_message_t_get_hash)
            return 0;
 
    const __lcm_hash_ptr cp = { p, (void*)__quad_mesh_message_t_get_hash };
    (void) cp;
 
    int64_t hash = 0x397798f0bfc5ee8fLL
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int64_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int64_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;
 
    return (hash<<1) + ((hash>>63)&1);
}
 
int64_t __quad_mesh_message_t_get_hash(void)
{
    if (!__quad_mesh_message_t_hash_computed) {
        __quad_mesh_message_t_hash = __quad_mesh_message_t_hash_recursive(NULL);
        __quad_mesh_message_t_hash_computed = 1;
    }
 
    return __quad_mesh_message_t_hash;
}
 
int __quad_mesh_message_t_encode_array(void *buf, int offset, int maxlen, const quad_mesh_message_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].image_width), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].image_height), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].image_size), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, p[element].image_data, p[element].image_size);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].num_vertices), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].vertex_x, p[element].num_vertices);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].vertex_y, p[element].num_vertices);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].vertex_z, p[element].num_vertices);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].tex_coord_x, p[element].num_vertices);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].tex_coord_y, p[element].num_vertices);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int quad_mesh_message_t_encode(void *buf, int offset, int maxlen, const quad_mesh_message_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __quad_mesh_message_t_get_hash();
 
    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    thislen = __quad_mesh_message_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int __quad_mesh_message_t_encoded_array_size(const quad_mesh_message_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {
 
        size += __int32_t_encoded_array_size(&(p[element].image_width), 1);
 
        size += __int32_t_encoded_array_size(&(p[element].image_height), 1);
 
        size += __int64_t_encoded_array_size(&(p[element].image_size), 1);
 
        size += __int8_t_encoded_array_size(p[element].image_data, p[element].image_size);
 
        size += __int64_t_encoded_array_size(&(p[element].num_vertices), 1);
 
        size += __float_encoded_array_size(p[element].vertex_x, p[element].num_vertices);
 
        size += __float_encoded_array_size(p[element].vertex_y, p[element].num_vertices);
 
        size += __float_encoded_array_size(p[element].vertex_z, p[element].num_vertices);
 
        size += __float_encoded_array_size(p[element].tex_coord_x, p[element].num_vertices);
 
        size += __float_encoded_array_size(p[element].tex_coord_y, p[element].num_vertices);
 
    }
    return size;
}
 
int quad_mesh_message_t_encoded_size(const quad_mesh_message_t *p)
{
    return 8 + __quad_mesh_message_t_encoded_array_size(p, 1);
}
 
int __quad_mesh_message_t_decode_array(const void *buf, int offset, int maxlen, quad_mesh_message_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].image_width), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].image_height), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].image_size), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].image_data = (int8_t*) lcm_malloc(sizeof(int8_t) * p[element].image_size);
        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, p[element].image_data, p[element].image_size);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].num_vertices), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].vertex_x = (float*) lcm_malloc(sizeof(float) * p[element].num_vertices);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].vertex_x, p[element].num_vertices);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].vertex_y = (float*) lcm_malloc(sizeof(float) * p[element].num_vertices);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].vertex_y, p[element].num_vertices);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].vertex_z = (float*) lcm_malloc(sizeof(float) * p[element].num_vertices);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].vertex_z, p[element].num_vertices);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].tex_coord_x = (float*) lcm_malloc(sizeof(float) * p[element].num_vertices);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].tex_coord_x, p[element].num_vertices);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].tex_coord_y = (float*) lcm_malloc(sizeof(float) * p[element].num_vertices);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].tex_coord_y, p[element].num_vertices);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int __quad_mesh_message_t_decode_array_cleanup(quad_mesh_message_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int32_t_decode_array_cleanup(&(p[element].image_width), 1);
 
        __int32_t_decode_array_cleanup(&(p[element].image_height), 1);
 
        __int64_t_decode_array_cleanup(&(p[element].image_size), 1);
 
        __int8_t_decode_array_cleanup(p[element].image_data, p[element].image_size);
        if (p[element].image_data) free(p[element].image_data);
 
        __int64_t_decode_array_cleanup(&(p[element].num_vertices), 1);
 
        __float_decode_array_cleanup(p[element].vertex_x, p[element].num_vertices);
        if (p[element].vertex_x) free(p[element].vertex_x);
 
        __float_decode_array_cleanup(p[element].vertex_y, p[element].num_vertices);
        if (p[element].vertex_y) free(p[element].vertex_y);
 
        __float_decode_array_cleanup(p[element].vertex_z, p[element].num_vertices);
        if (p[element].vertex_z) free(p[element].vertex_z);
 
        __float_decode_array_cleanup(p[element].tex_coord_x, p[element].num_vertices);
        if (p[element].tex_coord_x) free(p[element].tex_coord_x);
 
        __float_decode_array_cleanup(p[element].tex_coord_y, p[element].num_vertices);
        if (p[element].tex_coord_y) free(p[element].tex_coord_y);
 
    }
    return 0;
}
 
int quad_mesh_message_t_decode(const void *buf, int offset, int maxlen, quad_mesh_message_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __quad_mesh_message_t_get_hash();
 
    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;
 
    thislen = __quad_mesh_message_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int quad_mesh_message_t_decode_cleanup(quad_mesh_message_t *p)
{
    return __quad_mesh_message_t_decode_array_cleanup(p, 1);
}
 
int __quad_mesh_message_t_clone_array(const quad_mesh_message_t *p, quad_mesh_message_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int32_t_clone_array(&(p[element].image_width), &(q[element].image_width), 1);
 
        __int32_t_clone_array(&(p[element].image_height), &(q[element].image_height), 1);
 
        __int64_t_clone_array(&(p[element].image_size), &(q[element].image_size), 1);
 
        q[element].image_data = (int8_t*) lcm_malloc(sizeof(int8_t) * q[element].image_size);
        __int8_t_clone_array(p[element].image_data, q[element].image_data, p[element].image_size);
 
        __int64_t_clone_array(&(p[element].num_vertices), &(q[element].num_vertices), 1);
 
        q[element].vertex_x = (float*) lcm_malloc(sizeof(float) * q[element].num_vertices);
        __float_clone_array(p[element].vertex_x, q[element].vertex_x, p[element].num_vertices);
 
        q[element].vertex_y = (float*) lcm_malloc(sizeof(float) * q[element].num_vertices);
        __float_clone_array(p[element].vertex_y, q[element].vertex_y, p[element].num_vertices);
 
        q[element].vertex_z = (float*) lcm_malloc(sizeof(float) * q[element].num_vertices);
        __float_clone_array(p[element].vertex_z, q[element].vertex_z, p[element].num_vertices);
 
        q[element].tex_coord_x = (float*) lcm_malloc(sizeof(float) * q[element].num_vertices);
        __float_clone_array(p[element].tex_coord_x, q[element].tex_coord_x, p[element].num_vertices);
 
        q[element].tex_coord_y = (float*) lcm_malloc(sizeof(float) * q[element].num_vertices);
        __float_clone_array(p[element].tex_coord_y, q[element].tex_coord_y, p[element].num_vertices);
 
    }
    return 0;
}
 
quad_mesh_message_t *quad_mesh_message_t_copy(const quad_mesh_message_t *p)
{
    quad_mesh_message_t *q = (quad_mesh_message_t*) malloc(sizeof(quad_mesh_message_t));
    __quad_mesh_message_t_clone_array(p, q, 1);
    return q;
}
 
void quad_mesh_message_t_destroy(quad_mesh_message_t *p)
{
    __quad_mesh_message_t_decode_array_cleanup(p, 1);
    free(p);
}
 
int quad_mesh_message_t_publish(lcm_t *lc, const char *channel, const quad_mesh_message_t *p)
{
      int max_data_size = quad_mesh_message_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = quad_mesh_message_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _quad_mesh_message_t_subscription_t {
    quad_mesh_message_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void quad_mesh_message_t_handler_stub (const lcm_recv_buf_t *rbuf, 
                            const char *channel, void *userdata)
{
    int status;
    quad_mesh_message_t p;
    memset(&p, 0, sizeof(quad_mesh_message_t));
    status = quad_mesh_message_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding quad_mesh_message_t!!!\n", status);
        return;
    }

    quad_mesh_message_t_subscription_t *h = (quad_mesh_message_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    quad_mesh_message_t_decode_cleanup (&p);
}

quad_mesh_message_t_subscription_t* quad_mesh_message_t_subscribe (lcm_t *lcm, 
                    const char *channel, 
                    quad_mesh_message_t_handler_t f, void *userdata)
{
    quad_mesh_message_t_subscription_t *n = (quad_mesh_message_t_subscription_t*)
                       malloc(sizeof(quad_mesh_message_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel, 
                                 quad_mesh_message_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg quad_mesh_message_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int quad_mesh_message_t_unsubscribe(lcm_t *lcm, quad_mesh_message_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr, 
           "couldn't unsubscribe quad_mesh_message_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

