/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "target_position_message_t.h"

static int __target_position_message_t_hash_computed;
static int64_t __target_position_message_t_hash;
 
int64_t __target_position_message_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __target_position_message_t_get_hash)
            return 0;
 
    const __lcm_hash_ptr cp = { p, (void*)__target_position_message_t_get_hash };
    (void) cp;
 
    int64_t hash = 0xd259512e30b44885LL
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
        ;
 
    return (hash<<1) + ((hash>>63)&1);
}
 
int64_t __target_position_message_t_get_hash(void)
{
    if (!__target_position_message_t_hash_computed) {
        __target_position_message_t_hash = __target_position_message_t_hash_recursive(NULL);
        __target_position_message_t_hash_computed = 1;
    }
 
    return __target_position_message_t_hash;
}
 
int __target_position_message_t_encode_array(void *buf, int offset, int maxlen, const target_position_message_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int target_position_message_t_encode(void *buf, int offset, int maxlen, const target_position_message_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __target_position_message_t_get_hash();
 
    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    thislen = __target_position_message_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int __target_position_message_t_encoded_array_size(const target_position_message_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {
 
        size += __double_encoded_array_size(&(p[element].x), 1);
 
        size += __double_encoded_array_size(&(p[element].y), 1);
 
    }
    return size;
}
 
int target_position_message_t_encoded_size(const target_position_message_t *p)
{
    return 8 + __target_position_message_t_encoded_array_size(p, 1);
}
 
int __target_position_message_t_decode_array(const void *buf, int offset, int maxlen, target_position_message_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int __target_position_message_t_decode_array_cleanup(target_position_message_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __double_decode_array_cleanup(&(p[element].x), 1);
 
        __double_decode_array_cleanup(&(p[element].y), 1);
 
    }
    return 0;
}
 
int target_position_message_t_decode(const void *buf, int offset, int maxlen, target_position_message_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __target_position_message_t_get_hash();
 
    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;
 
    thislen = __target_position_message_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int target_position_message_t_decode_cleanup(target_position_message_t *p)
{
    return __target_position_message_t_decode_array_cleanup(p, 1);
}
 
int __target_position_message_t_clone_array(const target_position_message_t *p, target_position_message_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __double_clone_array(&(p[element].x), &(q[element].x), 1);
 
        __double_clone_array(&(p[element].y), &(q[element].y), 1);
 
    }
    return 0;
}
 
target_position_message_t *target_position_message_t_copy(const target_position_message_t *p)
{
    target_position_message_t *q = (target_position_message_t*) malloc(sizeof(target_position_message_t));
    __target_position_message_t_clone_array(p, q, 1);
    return q;
}
 
void target_position_message_t_destroy(target_position_message_t *p)
{
    __target_position_message_t_decode_array_cleanup(p, 1);
    free(p);
}
 
int target_position_message_t_publish(lcm_t *lc, const char *channel, const target_position_message_t *p)
{
      int max_data_size = target_position_message_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = target_position_message_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _target_position_message_t_subscription_t {
    target_position_message_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void target_position_message_t_handler_stub (const lcm_recv_buf_t *rbuf, 
                            const char *channel, void *userdata)
{
    int status;
    target_position_message_t p;
    memset(&p, 0, sizeof(target_position_message_t));
    status = target_position_message_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding target_position_message_t!!!\n", status);
        return;
    }

    target_position_message_t_subscription_t *h = (target_position_message_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    target_position_message_t_decode_cleanup (&p);
}

target_position_message_t_subscription_t* target_position_message_t_subscribe (lcm_t *lcm, 
                    const char *channel, 
                    target_position_message_t_handler_t f, void *userdata)
{
    target_position_message_t_subscription_t *n = (target_position_message_t_subscription_t*)
                       malloc(sizeof(target_position_message_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel, 
                                 target_position_message_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg target_position_message_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int target_position_message_t_unsubscribe(lcm_t *lcm, target_position_message_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr, 
           "couldn't unsubscribe target_position_message_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

