/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _texture_facet_t_h
#define _texture_facet_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _texture_facet_t texture_facet_t;
struct _texture_facet_t
{
    int64_t    patch_idx;
    int8_t     facet_idx;
    float      tex_coords[8];
    int8_t     labeled;
};
 
texture_facet_t   *texture_facet_t_copy(const texture_facet_t *p);
void texture_facet_t_destroy(texture_facet_t *p);

typedef struct _texture_facet_t_subscription_t texture_facet_t_subscription_t;
typedef void(*texture_facet_t_handler_t)(const lcm_recv_buf_t *rbuf, 
             const char *channel, const texture_facet_t *msg, void *user);

int texture_facet_t_publish(lcm_t *lcm, const char *channel, const texture_facet_t *p);
texture_facet_t_subscription_t* texture_facet_t_subscribe(lcm_t *lcm, const char *channel, texture_facet_t_handler_t f, void *userdata);
int texture_facet_t_unsubscribe(lcm_t *lcm, texture_facet_t_subscription_t* hid);

int  texture_facet_t_encode(void *buf, int offset, int maxlen, const texture_facet_t *p);
int  texture_facet_t_decode(const void *buf, int offset, int maxlen, texture_facet_t *p);
int  texture_facet_t_decode_cleanup(texture_facet_t *p);
int  texture_facet_t_encoded_size(const texture_facet_t *p);

// LCM support functions. Users should not call these
int64_t __texture_facet_t_get_hash(void);
int64_t __texture_facet_t_hash_recursive(const __lcm_hash_ptr *p);
int     __texture_facet_t_encode_array(void *buf, int offset, int maxlen, const texture_facet_t *p, int elements);
int     __texture_facet_t_decode_array(const void *buf, int offset, int maxlen, texture_facet_t *p, int elements);
int     __texture_facet_t_decode_array_cleanup(texture_facet_t *p, int elements);
int     __texture_facet_t_encoded_array_size(const texture_facet_t *p, int elements);
int     __texture_facet_t_clone_array(const texture_facet_t *p, texture_facet_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
