/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "texture_facet_t.h"

static int __texture_facet_t_hash_computed;
static int64_t __texture_facet_t_hash;
 
int64_t __texture_facet_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __texture_facet_t_get_hash)
            return 0;
 
    const __lcm_hash_ptr cp = { p, (void*)__texture_facet_t_get_hash };
    (void) cp;
 
    int64_t hash = 0xc3ece36914eec390LL
         + __int64_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __boolean_hash_recursive(&cp)
        ;
 
    return (hash<<1) + ((hash>>63)&1);
}
 
int64_t __texture_facet_t_get_hash(void)
{
    if (!__texture_facet_t_hash_computed) {
        __texture_facet_t_hash = __texture_facet_t_hash_recursive(NULL);
        __texture_facet_t_hash_computed = 1;
    }
 
    return __texture_facet_t_hash;
}
 
int __texture_facet_t_encode_array(void *buf, int offset, int maxlen, const texture_facet_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].patch_idx), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].facet_idx), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].tex_coords, 8);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &(p[element].labeled), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int texture_facet_t_encode(void *buf, int offset, int maxlen, const texture_facet_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __texture_facet_t_get_hash();
 
    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    thislen = __texture_facet_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int __texture_facet_t_encoded_array_size(const texture_facet_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {
 
        size += __int64_t_encoded_array_size(&(p[element].patch_idx), 1);
 
        size += __int8_t_encoded_array_size(&(p[element].facet_idx), 1);
 
        size += __float_encoded_array_size(p[element].tex_coords, 8);
 
        size += __boolean_encoded_array_size(&(p[element].labeled), 1);
 
    }
    return size;
}
 
int texture_facet_t_encoded_size(const texture_facet_t *p)
{
    return 8 + __texture_facet_t_encoded_array_size(p, 1);
}
 
int __texture_facet_t_decode_array(const void *buf, int offset, int maxlen, texture_facet_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].patch_idx), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].facet_idx), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].tex_coords, 8);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &(p[element].labeled), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int __texture_facet_t_decode_array_cleanup(texture_facet_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int64_t_decode_array_cleanup(&(p[element].patch_idx), 1);
 
        __int8_t_decode_array_cleanup(&(p[element].facet_idx), 1);
 
        __float_decode_array_cleanup(p[element].tex_coords, 8);
 
        __boolean_decode_array_cleanup(&(p[element].labeled), 1);
 
    }
    return 0;
}
 
int texture_facet_t_decode(const void *buf, int offset, int maxlen, texture_facet_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __texture_facet_t_get_hash();
 
    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;
 
    thislen = __texture_facet_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int texture_facet_t_decode_cleanup(texture_facet_t *p)
{
    return __texture_facet_t_decode_array_cleanup(p, 1);
}
 
int __texture_facet_t_clone_array(const texture_facet_t *p, texture_facet_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int64_t_clone_array(&(p[element].patch_idx), &(q[element].patch_idx), 1);
 
        __int8_t_clone_array(&(p[element].facet_idx), &(q[element].facet_idx), 1);
 
        __float_clone_array(p[element].tex_coords, q[element].tex_coords, 8);
 
        __boolean_clone_array(&(p[element].labeled), &(q[element].labeled), 1);
 
    }
    return 0;
}
 
texture_facet_t *texture_facet_t_copy(const texture_facet_t *p)
{
    texture_facet_t *q = (texture_facet_t*) malloc(sizeof(texture_facet_t));
    __texture_facet_t_clone_array(p, q, 1);
    return q;
}
 
void texture_facet_t_destroy(texture_facet_t *p)
{
    __texture_facet_t_decode_array_cleanup(p, 1);
    free(p);
}
 
int texture_facet_t_publish(lcm_t *lc, const char *channel, const texture_facet_t *p)
{
      int max_data_size = texture_facet_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = texture_facet_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _texture_facet_t_subscription_t {
    texture_facet_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void texture_facet_t_handler_stub (const lcm_recv_buf_t *rbuf, 
                            const char *channel, void *userdata)
{
    int status;
    texture_facet_t p;
    memset(&p, 0, sizeof(texture_facet_t));
    status = texture_facet_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding texture_facet_t!!!\n", status);
        return;
    }

    texture_facet_t_subscription_t *h = (texture_facet_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    texture_facet_t_decode_cleanup (&p);
}

texture_facet_t_subscription_t* texture_facet_t_subscribe (lcm_t *lcm, 
                    const char *channel, 
                    texture_facet_t_handler_t f, void *userdata)
{
    texture_facet_t_subscription_t *n = (texture_facet_t_subscription_t*)
                       malloc(sizeof(texture_facet_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel, 
                                 texture_facet_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg texture_facet_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int texture_facet_t_unsubscribe(lcm_t *lcm, texture_facet_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr, 
           "couldn't unsubscribe texture_facet_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

