/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "texture_map_message_t.h"

static int __texture_map_message_t_hash_computed;
static int64_t __texture_map_message_t_hash;
 
int64_t __texture_map_message_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __texture_map_message_t_get_hash)
            return 0;
 
    const __lcm_hash_ptr cp = { p, (void*)__texture_map_message_t_get_hash };
    (void) cp;
 
    int64_t hash = 0xb26175312ba24758LL
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int64_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int64_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int64_t_hash_recursive(&cp)
         + __texture_facet_t_hash_recursive(&cp)
        ;
 
    return (hash<<1) + ((hash>>63)&1);
}
 
int64_t __texture_map_message_t_get_hash(void)
{
    if (!__texture_map_message_t_hash_computed) {
        __texture_map_message_t_hash = __texture_map_message_t_hash_recursive(NULL);
        __texture_map_message_t_hash_computed = 1;
    }
 
    return __texture_map_message_t_hash;
}
 
int __texture_map_message_t_encode_array(void *buf, int offset, int maxlen, const texture_map_message_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].seq_no), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].image_width), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].image_height), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].image_size), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, p[element].image_data, p[element].image_size);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].patch_resolution), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].num_patches), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        { int a;
        for (a = 0; a < p[element].num_patches; a++) {
            thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].patches[a], 4);
            if (thislen < 0) return thislen; else pos += thislen;
        }
        }
 
        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].num_tex_facets), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __texture_facet_t_encode_array(buf, offset + pos, maxlen - pos, p[element].tex_facets, p[element].num_tex_facets);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int texture_map_message_t_encode(void *buf, int offset, int maxlen, const texture_map_message_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __texture_map_message_t_get_hash();
 
    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    thislen = __texture_map_message_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int __texture_map_message_t_encoded_array_size(const texture_map_message_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {
 
        size += __int32_t_encoded_array_size(&(p[element].seq_no), 1);
 
        size += __int32_t_encoded_array_size(&(p[element].image_width), 1);
 
        size += __int32_t_encoded_array_size(&(p[element].image_height), 1);
 
        size += __int64_t_encoded_array_size(&(p[element].image_size), 1);
 
        size += __int8_t_encoded_array_size(p[element].image_data, p[element].image_size);
 
        size += __float_encoded_array_size(&(p[element].patch_resolution), 1);
 
        size += __int64_t_encoded_array_size(&(p[element].num_patches), 1);
 
        { int a;
        for (a = 0; a < p[element].num_patches; a++) {
            size += __float_encoded_array_size(p[element].patches[a], 4);
        }
        }
 
        size += __int64_t_encoded_array_size(&(p[element].num_tex_facets), 1);
 
        size += __texture_facet_t_encoded_array_size(p[element].tex_facets, p[element].num_tex_facets);
 
    }
    return size;
}
 
int texture_map_message_t_encoded_size(const texture_map_message_t *p)
{
    return 8 + __texture_map_message_t_encoded_array_size(p, 1);
}
 
int __texture_map_message_t_decode_array(const void *buf, int offset, int maxlen, texture_map_message_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].seq_no), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].image_width), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].image_height), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].image_size), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].image_data = (int8_t*) lcm_malloc(sizeof(int8_t) * p[element].image_size);
        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, p[element].image_data, p[element].image_size);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].patch_resolution), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].num_patches), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].patches = (float**) lcm_malloc(sizeof(float*) * p[element].num_patches);
        { int a;
        for (a = 0; a < p[element].num_patches; a++) {
            p[element].patches[a] = (float*) lcm_malloc(sizeof(float) * 4);
            thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].patches[a], 4);
            if (thislen < 0) return thislen; else pos += thislen;
        }
        }
 
        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].num_tex_facets), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].tex_facets = (texture_facet_t*) lcm_malloc(sizeof(texture_facet_t) * p[element].num_tex_facets);
        thislen = __texture_facet_t_decode_array(buf, offset + pos, maxlen - pos, p[element].tex_facets, p[element].num_tex_facets);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int __texture_map_message_t_decode_array_cleanup(texture_map_message_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int32_t_decode_array_cleanup(&(p[element].seq_no), 1);
 
        __int32_t_decode_array_cleanup(&(p[element].image_width), 1);
 
        __int32_t_decode_array_cleanup(&(p[element].image_height), 1);
 
        __int64_t_decode_array_cleanup(&(p[element].image_size), 1);
 
        __int8_t_decode_array_cleanup(p[element].image_data, p[element].image_size);
        if (p[element].image_data) free(p[element].image_data);
 
        __float_decode_array_cleanup(&(p[element].patch_resolution), 1);
 
        __int64_t_decode_array_cleanup(&(p[element].num_patches), 1);
 
        { int a;
        for (a = 0; a < p[element].num_patches; a++) {
            __float_decode_array_cleanup(p[element].patches[a], 4);
            if (p[element].patches[a]) free(p[element].patches[a]);
        }
        }
        if (p[element].patches) free(p[element].patches);
 
        __int64_t_decode_array_cleanup(&(p[element].num_tex_facets), 1);
 
        __texture_facet_t_decode_array_cleanup(p[element].tex_facets, p[element].num_tex_facets);
        if (p[element].tex_facets) free(p[element].tex_facets);
 
    }
    return 0;
}
 
int texture_map_message_t_decode(const void *buf, int offset, int maxlen, texture_map_message_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __texture_map_message_t_get_hash();
 
    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;
 
    thislen = __texture_map_message_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int texture_map_message_t_decode_cleanup(texture_map_message_t *p)
{
    return __texture_map_message_t_decode_array_cleanup(p, 1);
}
 
int __texture_map_message_t_clone_array(const texture_map_message_t *p, texture_map_message_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int32_t_clone_array(&(p[element].seq_no), &(q[element].seq_no), 1);
 
        __int32_t_clone_array(&(p[element].image_width), &(q[element].image_width), 1);
 
        __int32_t_clone_array(&(p[element].image_height), &(q[element].image_height), 1);
 
        __int64_t_clone_array(&(p[element].image_size), &(q[element].image_size), 1);
 
        q[element].image_data = (int8_t*) lcm_malloc(sizeof(int8_t) * q[element].image_size);
        __int8_t_clone_array(p[element].image_data, q[element].image_data, p[element].image_size);
 
        __float_clone_array(&(p[element].patch_resolution), &(q[element].patch_resolution), 1);
 
        __int64_t_clone_array(&(p[element].num_patches), &(q[element].num_patches), 1);
 
        q[element].patches = (float**) lcm_malloc(sizeof(float*) * q[element].num_patches);
        { int a;
        for (a = 0; a < p[element].num_patches; a++) {
            q[element].patches[a] = (float*) lcm_malloc(sizeof(float) * 4);
            __float_clone_array(p[element].patches[a], q[element].patches[a], 4);
        }
        }
 
        __int64_t_clone_array(&(p[element].num_tex_facets), &(q[element].num_tex_facets), 1);
 
        q[element].tex_facets = (texture_facet_t*) lcm_malloc(sizeof(texture_facet_t) * q[element].num_tex_facets);
        __texture_facet_t_clone_array(p[element].tex_facets, q[element].tex_facets, p[element].num_tex_facets);
 
    }
    return 0;
}
 
texture_map_message_t *texture_map_message_t_copy(const texture_map_message_t *p)
{
    texture_map_message_t *q = (texture_map_message_t*) malloc(sizeof(texture_map_message_t));
    __texture_map_message_t_clone_array(p, q, 1);
    return q;
}
 
void texture_map_message_t_destroy(texture_map_message_t *p)
{
    __texture_map_message_t_decode_array_cleanup(p, 1);
    free(p);
}
 
int texture_map_message_t_publish(lcm_t *lc, const char *channel, const texture_map_message_t *p)
{
      int max_data_size = texture_map_message_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = texture_map_message_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _texture_map_message_t_subscription_t {
    texture_map_message_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void texture_map_message_t_handler_stub (const lcm_recv_buf_t *rbuf, 
                            const char *channel, void *userdata)
{
    int status;
    texture_map_message_t p;
    memset(&p, 0, sizeof(texture_map_message_t));
    status = texture_map_message_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding texture_map_message_t!!!\n", status);
        return;
    }

    texture_map_message_t_subscription_t *h = (texture_map_message_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    texture_map_message_t_decode_cleanup (&p);
}

texture_map_message_t_subscription_t* texture_map_message_t_subscribe (lcm_t *lcm, 
                    const char *channel, 
                    texture_map_message_t_handler_t f, void *userdata)
{
    texture_map_message_t_subscription_t *n = (texture_map_message_t_subscription_t*)
                       malloc(sizeof(texture_map_message_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel, 
                                 texture_map_message_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg texture_map_message_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int texture_map_message_t_unsubscribe(lcm_t *lcm, texture_map_message_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr, 
           "couldn't unsubscribe texture_map_message_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

