/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _texture_map_message_t_h
#define _texture_map_message_t_h

#ifdef __cplusplus
extern "C" {
#endif

#include "texture_facet_t.h"
typedef struct _texture_map_message_t texture_map_message_t;
struct _texture_map_message_t
{
    int32_t    seq_no;
    int32_t    image_width;
    int32_t    image_height;
    int64_t    image_size;
    int8_t     *image_data;
    float      patch_resolution;
    int64_t    num_patches;
    float      **patches;
    int64_t    num_tex_facets;
    texture_facet_t *tex_facets;
};
 
texture_map_message_t   *texture_map_message_t_copy(const texture_map_message_t *p);
void texture_map_message_t_destroy(texture_map_message_t *p);

typedef struct _texture_map_message_t_subscription_t texture_map_message_t_subscription_t;
typedef void(*texture_map_message_t_handler_t)(const lcm_recv_buf_t *rbuf, 
             const char *channel, const texture_map_message_t *msg, void *user);

int texture_map_message_t_publish(lcm_t *lcm, const char *channel, const texture_map_message_t *p);
texture_map_message_t_subscription_t* texture_map_message_t_subscribe(lcm_t *lcm, const char *channel, texture_map_message_t_handler_t f, void *userdata);
int texture_map_message_t_unsubscribe(lcm_t *lcm, texture_map_message_t_subscription_t* hid);

int  texture_map_message_t_encode(void *buf, int offset, int maxlen, const texture_map_message_t *p);
int  texture_map_message_t_decode(const void *buf, int offset, int maxlen, texture_map_message_t *p);
int  texture_map_message_t_decode_cleanup(texture_map_message_t *p);
int  texture_map_message_t_encoded_size(const texture_map_message_t *p);

// LCM support functions. Users should not call these
int64_t __texture_map_message_t_get_hash(void);
int64_t __texture_map_message_t_hash_recursive(const __lcm_hash_ptr *p);
int     __texture_map_message_t_encode_array(void *buf, int offset, int maxlen, const texture_map_message_t *p, int elements);
int     __texture_map_message_t_decode_array(const void *buf, int offset, int maxlen, texture_map_message_t *p, int elements);
int     __texture_map_message_t_decode_array_cleanup(texture_map_message_t *p, int elements);
int     __texture_map_message_t_encoded_array_size(const texture_map_message_t *p, int elements);
int     __texture_map_message_t_clone_array(const texture_map_message_t *p, texture_map_message_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
