/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "virtual_scan_message_t.h"

static int __virtual_scan_message_t_hash_computed;
static int64_t __virtual_scan_message_t_hash;
 
int64_t __virtual_scan_message_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __virtual_scan_message_t_get_hash)
            return 0;
 
    const __lcm_hash_ptr cp = { p, (void*)__virtual_scan_message_t_get_hash };
    (void) cp;
 
    int64_t hash = 0x800aed8bad997402LL
         + __int64_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
        ;
 
    return (hash<<1) + ((hash>>63)&1);
}
 
int64_t __virtual_scan_message_t_get_hash(void)
{
    if (!__virtual_scan_message_t_hash_computed) {
        __virtual_scan_message_t_hash = __virtual_scan_message_t_hash_recursive(NULL);
        __virtual_scan_message_t_hash_computed = 1;
    }
 
    return __virtual_scan_message_t_hash;
}
 
int __virtual_scan_message_t_encode_array(void *buf, int offset, int maxlen, const virtual_scan_message_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].angular_resolution), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].origin, 3);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].num_rays), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        { int a;
        for (a = 0; a < p[element].num_rays; a++) {
            thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].ray_endpoints[a], 3);
            if (thislen < 0) return thislen; else pos += thislen;
        }
        }
 
    }
    return pos;
}
 
int virtual_scan_message_t_encode(void *buf, int offset, int maxlen, const virtual_scan_message_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __virtual_scan_message_t_get_hash();
 
    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    thislen = __virtual_scan_message_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int __virtual_scan_message_t_encoded_array_size(const virtual_scan_message_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {
 
        size += __int64_t_encoded_array_size(&(p[element].utime), 1);
 
        size += __float_encoded_array_size(&(p[element].angular_resolution), 1);
 
        size += __double_encoded_array_size(p[element].origin, 3);
 
        size += __int32_t_encoded_array_size(&(p[element].num_rays), 1);
 
        { int a;
        for (a = 0; a < p[element].num_rays; a++) {
            size += __int16_t_encoded_array_size(p[element].ray_endpoints[a], 3);
        }
        }
 
    }
    return size;
}
 
int virtual_scan_message_t_encoded_size(const virtual_scan_message_t *p)
{
    return 8 + __virtual_scan_message_t_encoded_array_size(p, 1);
}
 
int __virtual_scan_message_t_decode_array(const void *buf, int offset, int maxlen, virtual_scan_message_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].angular_resolution), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].origin, 3);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].num_rays), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].ray_endpoints = (int16_t**) lcm_malloc(sizeof(int16_t*) * p[element].num_rays);
        { int a;
        for (a = 0; a < p[element].num_rays; a++) {
            p[element].ray_endpoints[a] = (int16_t*) lcm_malloc(sizeof(int16_t) * 3);
            thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].ray_endpoints[a], 3);
            if (thislen < 0) return thislen; else pos += thislen;
        }
        }
 
    }
    return pos;
}
 
int __virtual_scan_message_t_decode_array_cleanup(virtual_scan_message_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int64_t_decode_array_cleanup(&(p[element].utime), 1);
 
        __float_decode_array_cleanup(&(p[element].angular_resolution), 1);
 
        __double_decode_array_cleanup(p[element].origin, 3);
 
        __int32_t_decode_array_cleanup(&(p[element].num_rays), 1);
 
        { int a;
        for (a = 0; a < p[element].num_rays; a++) {
            __int16_t_decode_array_cleanup(p[element].ray_endpoints[a], 3);
            if (p[element].ray_endpoints[a]) free(p[element].ray_endpoints[a]);
        }
        }
        if (p[element].ray_endpoints) free(p[element].ray_endpoints);
 
    }
    return 0;
}
 
int virtual_scan_message_t_decode(const void *buf, int offset, int maxlen, virtual_scan_message_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __virtual_scan_message_t_get_hash();
 
    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;
 
    thislen = __virtual_scan_message_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int virtual_scan_message_t_decode_cleanup(virtual_scan_message_t *p)
{
    return __virtual_scan_message_t_decode_array_cleanup(p, 1);
}
 
int __virtual_scan_message_t_clone_array(const virtual_scan_message_t *p, virtual_scan_message_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);
 
        __float_clone_array(&(p[element].angular_resolution), &(q[element].angular_resolution), 1);
 
        __double_clone_array(p[element].origin, q[element].origin, 3);
 
        __int32_t_clone_array(&(p[element].num_rays), &(q[element].num_rays), 1);
 
        q[element].ray_endpoints = (int16_t**) lcm_malloc(sizeof(int16_t*) * q[element].num_rays);
        { int a;
        for (a = 0; a < p[element].num_rays; a++) {
            q[element].ray_endpoints[a] = (int16_t*) lcm_malloc(sizeof(int16_t) * 3);
            __int16_t_clone_array(p[element].ray_endpoints[a], q[element].ray_endpoints[a], 3);
        }
        }
 
    }
    return 0;
}
 
virtual_scan_message_t *virtual_scan_message_t_copy(const virtual_scan_message_t *p)
{
    virtual_scan_message_t *q = (virtual_scan_message_t*) malloc(sizeof(virtual_scan_message_t));
    __virtual_scan_message_t_clone_array(p, q, 1);
    return q;
}
 
void virtual_scan_message_t_destroy(virtual_scan_message_t *p)
{
    __virtual_scan_message_t_decode_array_cleanup(p, 1);
    free(p);
}
 
int virtual_scan_message_t_publish(lcm_t *lc, const char *channel, const virtual_scan_message_t *p)
{
      int max_data_size = virtual_scan_message_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = virtual_scan_message_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _virtual_scan_message_t_subscription_t {
    virtual_scan_message_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void virtual_scan_message_t_handler_stub (const lcm_recv_buf_t *rbuf, 
                            const char *channel, void *userdata)
{
    int status;
    virtual_scan_message_t p;
    memset(&p, 0, sizeof(virtual_scan_message_t));
    status = virtual_scan_message_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding virtual_scan_message_t!!!\n", status);
        return;
    }

    virtual_scan_message_t_subscription_t *h = (virtual_scan_message_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    virtual_scan_message_t_decode_cleanup (&p);
}

virtual_scan_message_t_subscription_t* virtual_scan_message_t_subscribe (lcm_t *lcm, 
                    const char *channel, 
                    virtual_scan_message_t_handler_t f, void *userdata)
{
    virtual_scan_message_t_subscription_t *n = (virtual_scan_message_t_subscription_t*)
                       malloc(sizeof(virtual_scan_message_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel, 
                                 virtual_scan_message_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg virtual_scan_message_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int virtual_scan_message_t_unsubscribe(lcm_t *lcm, virtual_scan_message_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr, 
           "couldn't unsubscribe virtual_scan_message_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

